// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verto_Tech_Test.Data;

#nullable disable

namespace Verto_Tech_Test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711192956_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Verto_Tech_Test.Models.Domain.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e798495-bf06-41f8-845c-8d0826cc97bb"),
                            Description = "Lorem ipsum dolor sit amet, id per dictas inermis. Eam odio modo cibo at. Purto dignissim euripidis eu mel, cu mel.",
                            ImageUrl = "https://placehold.co/300x230",
                            Title = "New Products"
                        },
                        new
                        {
                            Id = new Guid("aae16c1b-164a-4ce0-a993-893b81ad2594"),
                            Description = "Lorem ipsum dolor sit amet, id per dictas inermis. Eam odio modo cibo at. Purto dignissim euripidis eu mel, cu mel.",
                            ImageUrl = "https://placehold.co/300x230",
                            Title = "Field Events"
                        },
                        new
                        {
                            Id = new Guid("d2ef780d-5415-447d-a283-ee0cd585f6d9"),
                            Description = "Lorem ipsum dolor sit amet, id per dictas inermis. Eam odio modo cibo at. Purto dignissim euripidis eu mel, cu mel.",
                            ImageUrl = "https://placehold.co/300x230",
                            Title = "Latest News"
                        },
                        new
                        {
                            Id = new Guid("8dde77e0-40e2-4487-8d1f-8cc7d605020d"),
                            Description = "Lorem ipsum dolor sit amet, id per dictas inermis. Eam odio modo cibo at. Purto dignissim euripidis eu mel, cu mel.",
                            ImageUrl = "https://placehold.co/300x230",
                            Title = "Gallery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
